### ISSUE TITLE
Place order with StopLoss and TakeProfit arguments

### ISSUE THREAD

**Issue by ericyam94** [tedchou12/webull#182]
In place_order function there is no stoploss and takeprofile arguments to pass in. 
Whereas in Webull itself it can set those value.
Is there a way to set it?

**Comment by haroonismailbasha** [comment]
Were you able to place order? Did it work? Im seeing below error after trading hours.

Service is not available,please try again later

**Comment by tedchou12** [comment]
If you meant Stoploss, it should be possible:
https://github.com/tedchou12/webull/blob/613b3982f19bd40cc67a5de46557602f94693045/webull/webull.py#L396

```
price: float (LMT / STP LMT Only)
action: BUY / SELL
ordertype : LMT / MKT / STP / STP LMT / STP TRAIL
timeinforce:  GTC / DAY / IOC
outsideRegularTradingHour: True / False
stpPrice: float (STP / STP LMT Only)
trial_value: float (STP TRIAL Only)
trial_type: DOLLAR / PERCENTAGE (STP TRIAL Only)
```

Sorry, is not well documented, because webull is updating the endpoints so frequently, I am a bit hesitant to waste my time making efforts that I will need to changed afterwards.

**Comment by ericyam94** [comment]
This is what I looking for. Thanks..
