### ISSUE TITLE
any luck with accurate rsi calculation

### ISSUE THREAD

**Issue by jamesavilla** [tedchou12/webull#202]
@tedchou12 Hi, have you been able to accurately calculate rsi to match what webull is showing on their UI.  I cant seem to get the same values as they are showing on the rsi14 chart.

**Comment by tedchou12** [comment]
Hi!

Actually, I don't use that many indices myself. Can you take a screenshot on http://app.webull.com/ and let me know which part you are referring to?

**Comment by jamesavilla** [comment]
![Screen Shot 2021-03-08 at 11 47 23 AM](https://user-images.githubusercontent.com/6108832/110352809-5ccb8b80-8004-11eb-90b7-acbe88392d92.png)

**Comment by jamesavilla** [comment]
Hi Ted,

Any luck with this?

Thanks,
Jim

**Comment by hfacey** [comment]
we can't know for sure how webull calculates on their RSI on the backend, but it should be the standard way. See [this reference](https://www.fmlabs.com/reference/default.htm?url=RSI.htm) or [this article](https://www.investopedia.com/terms/r/rsi.asp) to ensure you're following the standard way

**Comment by tedchou12** [comment]
@jamesavilla 
I took a look at the browser requests. This data is not a GET or POST request. My best guess is that it is using stream or socket technologies to update the information automatically.

My honest opinion is try to think of the purpose of this package as to automate your trading, placing buy or sell orders for you. I don't recommend trying to take advantage of the APIs to fetch realtime or instant data from Webull, because this API is not official nor guaranteed. If your account gets flagged or blocked as a result of accessing the requests too often as a result of using this API, I will not be very surprised. As Robinhood seems to be actively doing that.

There are plentiful of data providers online like Yahoo finance or IEXCloud, and if you are confident in strategy to work, spending few dozen dollars per month on the data is not at all extravagant. And if you really want quality data, I don't recommend Webull too.

If you are paying Webull for Plan 2 data, well you are entitled to that data. But again, Webull does not provide API, so if you are paying for the data, why not go ahead and pay to the data providers who already support providing you the data via API?

Overall, for what you are doing, I recommend you to think again.

**Comment by tedchou12** [comment]
^ Sorry, if you are just wondering about the RSI value, I have not a clue. (hfacey's answer is great).

(This is just for people who are looking to access the data on webull.)

**Comment by mirkan1** [comment]
> we can't know for sure how webull calculates on their RSI on the backend, but it should be the standard way. See [this reference](https://www.fmlabs.com/reference/default.htm?url=RSI.htm) or [this article](https://www.investopedia.com/terms/r/rsi.asp) to ensure you're following the standard way

it's like gibberish to me

**Comment by hfacey** [comment]
> > we can't know for sure how webull calculates on their RSI on the backend, but it should be the standard way. See [this reference](https://www.fmlabs.com/reference/default.htm?url=RSI.htm) or [this article](https://www.investopedia.com/terms/r/rsi.asp) to ensure you're following the standard way
> 
> it's like gibberish to me

if you're gonna be a trader (an algo trader at that), you'll want to learn technical indicators... what they are, how they work, etc.

**Comment by mirkan1** [comment]
Maybe you can write an example script on Python language with a little variables so that I can understand. My math is really bad to understand such equations

> > > we can't know for sure how webull calculates on their RSI on the backend, but it should be the standard way. See [this reference](https://www.fmlabs.com/reference/default.htm?url=RSI.htm) or [this article](https://www.investopedia.com/terms/r/rsi.asp) to ensure you're following the standard way
> > 
> > 
> > it's like gibberish to me
> 
> if you're gonna be a trader (an algo trader at that), you'll want to learn technical indicators... what they are, how they work, etc.

**Comment by hfacey** [comment]
I don't think I could code anything that's simpler than that the [this article](https://www.investopedia.com/terms/r/rsi.asp). but if you really want to see how someone implements RSI in python [here's an example](https://github.com/bukosabino/ta/blob/master/ta/momentum.py#L14). 
Also, technical analysis is beyond the purview of this library. You can use a technical indicator/analysis library like the one I referenced above to perform all the common calculations you'd like
