### ISSUE TITLE
get_options_bars only returning last trade when direction=1

### ISSUE THREAD

**Issue by BigDaddyBastonkadonkz** [tedchou12/webull#262]
When I invoke get-options_bars with direction=1, it's supposed to return all data on or after the specified epoch date. However, it is only returning the last data point.

**Comment by zenhorace** [comment]
it's just a matter of which use case you optimize for. I think count=1 by default because the most common use case is fetching the most recent bar when trying to figure how to price a trade. I wouldn't consider having to specify an intended parameter a "workaround". 
But, your use case is one I have quite often. A tip: the max number of bars the API will ever return in 1 request is 800. So when I'm pulling all the options data from a contract, I always set count to 800 and loop (repeating the API call) until it returns less than 800, updating the timestamp each time.
