### ISSUE TITLE
Automatic Way To Refresh Access Token?

### ISSUE THREAD

**Issue by Alanavai** [tedchou12/webull#300]
Hello,

I've been using the workaround to refresh the access token by logging into Webull and copying the credentials in the inspector, but is there any currently working way this can be done automatically?

Thanks

**Comment by ssheikh098** [comment]
Hello,

Any specific reason you are using above manual way instead of calling login method of this code? I am using this package from some time now(almost year) and all the time I used login module. Let me know if any way I can help you. 

In my local copy of this package I did some modification as well. Some of the things I did, is checking token expire time and then calling login module 

This code written on old version of this package so there might be few functionality already added to this package however below code should work if you are using email MFA. also I am using outlook.com so if its gmail then related imap should be updated. 

Note - below code might have lot of dead code. Email read code copied from google and modified to read only email received from Webull based on subject and sender. 

call set_access_token method to load access token from pickle file saves after login, if there is no entry created yet, then call start session. Below code can be improved a lot but as its working for me I didn't spend time correcting code. 
Sample Program:
![image](https://user-images.githubusercontent.com/14261211/154610706-e70fe121-32b2-429a-9831-98dd4342c143.png)

Supporting program(Webull_Ext class)
![image](https://user-images.githubusercontent.com/14261211/154607716-31849a0e-0aa9-4027-baca-34c127cefabd.png)

![image](https://user-images.githubusercontent.com/14261211/154607950-78217a1e-e76a-4609-98a4-55450a3c27f2.png)


![image](https://user-images.githubusercontent.com/14261211/154608047-f1747b81-7f48-429b-9753-26fea585913f.png)

![image](https://user-images.githubusercontent.com/14261211/154608222-52280b9a-e4b1-4896-a790-17568e9d1e6b.png)

![image](https://user-images.githubusercontent.com/14261211/154608286-84401434-dcd5-45c2-ae5d-caf17b6a2280.png)

![image](https://user-images.githubusercontent.com/14261211/154608380-11efc3e7-9c20-4fe2-bee5-25ff18dd47b7.png)

I have added an additional parameter to login method as I have 2 account with Webull so to pick zone from first account I am passing 1

![image](https://user-images.githubusercontent.com/14261211/154611009-04da2ffd-03db-45b7-83ac-0083eb428fb8.png)

Thanks

**Comment by Alanavai** [comment]
Hi,

I appreciate the effort you put into your reply, thanks. However, I'm still a bit confused by all this custom stuff you added. Could you show me how to login and automatically refresh the access token using the built-in functionality of the webull class instead of showing your own class?
