### ISSUE TITLE
When placing order, outsideRegularTradingHour is default true

### ISSUE THREAD

**Issue by gamesover** [tedchou12/webull#38]
When I check the source code, I find when placing order, `'outsideRegularTradingHour': True`. May I ask what's the extra benefit to trade before or after regular market time?

May be it is a biz question more than coding question ;). Having extra hours to trade is always a good thing?

Shall we give people an option to trade only at market time?

**Comment by tedchou12** [comment]
I remember that was a request that was added later.
When using the Webull, you can place the order as trading hours only (9:30-4:00) or extended trading hour (8:00-9:30 and 4:00-5:00, this may depend on the market).
Trading in extend hours means you are allowed to trade outside the working hours of the stock market.
Long time ago, when the stock market is not digitized, trading was done in paper and people have to be physically present at the stock market or have a telephone line. Although now since everything is automized and online, the trading hour is much more vague, and if you would like, you can trade as long as you find a opposition party.
https://www.investopedia.com/terms/e/extended_trading.asp

One caution is that the price fluctuates more in the trading hours since more people are trading, if there is some information asymmetry, you may be trading without the full information on the price at the extended trading hours.

Since Webull allow people to trade outside the market hours, I guess is okay to keep it.

**Comment by gamesover** [comment]
https://github.com/tedchou12/webull/pull/39
