### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by c0debase** [tedchou12/webull#55]
Every time I try to login I get the error {'msg': 'deviceId=null','traceId':'xxx','code':'500'}

**Comment by tedchou12** [comment]
Hi There!
Does this solve the issue?
https://github.com/tedchou12/webull/wiki/MFA

**Comment by NathanHRich** [comment]
Looks like Webull changed their backend API. Device id is now required in the header when you login. I was having this same error. 
I added `headers['did'] = self._did` on line 110 of webull.py, right before the login POST, and was able to login successfully. 
It's also worth noting that the login response was returning a 500. But there isn't any error handling around the login POST so it was continuing anyway.

**Comment by TestyTesties** [comment]
@NathanHRich Holy cow you saved me from a major headache here, great find!

This also fixes the KeyError: 'secAccountId' error message if anyone comes across that.

**Comment by taeable** [comment]
Hey guys, I'm also having issues logging in
I run my code like this
###Code starts###
from webull import paper_webull

wb = paper_webull()
email = '<YOUR_WEBULL_EMAIL>'
password = '<YOUR_WEBULL_PASSWORD>'
device_name = 'linux_device' #name I set my device name to be added

#uncomment if mfa_key is known
mfa_key = '<YOUR_MFA_KEY>'

#uncomment if mfa_key is not known, then check your email and enter it into the prompt
#wb.get_mfa(email)
#mfa_key = input('What is your MFA key? ')

data = wb.login(email, password, device_name, mfa_key)
print(data)
###Code Ends###

I put in my <YOUR_MFA_KEY> in since I knew what my MFA key was.

Here is my output
ubuntu@ubuntu:~/git/algoTrader$ python3 webull_buy_paper.py
{'msg': 'Incorrect password. You have 3 attempts remaining.'', 'traceId': 'bs5468f864321c64f6646f', 'code': 'account.pwd.mismatch'}

I know what my password is, but I am still having issues logging in.

**Comment by c0debase** [comment]
Thank you all so very much and thank you Ted for making this excellent library.
